[project]
name = "openpi-vggt"
version = "1.0.0"
description = "OpenPi & VGGT-Omega"
requires-python = ">=3.11" #,<3.12"
dependencies = [
	"openpi",
	"vggt-omega"
]

[tool.uv]
override-dependencies = [
	"ml-dtypes==0.4.1", 
	"tensorstore==0.1.74"
]

[tool.uv.workspace]
members = [
	"openpi",
	"vggt-omega",
	"openpi/packages/*"
]

[tool.uv.sources]
openpi = {workspace = true}
vggt-omega = {workspace = true}

